In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('test_df.csv',  delimiter=';', encoding='latin-1')
df.tail()

Numéro de mesure  Longitude  Latitude  \
1509            160876    3.69500  43.39833   
1510            160877    3.95194  43.57361   
1511            160878    3.83972  43.60861   
1512            160879    4.00889  43.61667   
1513            160880    3.23083  43.35111   

                                       Position  Insee  \
1509  03° 41' 42.00'' Est, 43° 23' 54.00'' Nord  34301   
1510  03° 57' 07.00'' Est, 43° 34' 25.00'' Nord  34198   
1511  03° 50' 23.00'' Est, 43° 36' 31.00'' Nord  34172   
1512  04° 00' 32.00'' Est, 43° 37' 00.00'' Nord  34154   
1513  03° 13' 51.00'' Est, 43° 21' 04.00'' Nord  34032   

                            Adresse  \
1509                      Rue Lacan   
1510              Route de la Foire   
1511       888 Rue François Dezeuze   
1512         Place de la Libération   
1513  2 Avenue Ferdinand de Lesseps   

                                             Complément  Code postal  \
1509          Ecole Colbert, dans la cour côté toboggan        34200   
1510  Arena, 2ème étage, dans l'open-space, devant l...        34470   
1511  Résidence Les Portes de la Martelle, 5ème étag...        34070   
1512  Hôtel de Ville, au 2ème étage, dans le bureau ...        34130   
1513  Clinique La Pergola, 3ème étage, dans l'infirm...        34500   

          Commune Date de mesure Mesure réalisée               Rapport  \
1509         SETE     26/01/2011    En intérieur  FicheMesure22461.pdf   
1510       PEROLS     14/02/2011    En intérieur  FicheMesure22733.pdf   
1511  MONTPELLIER     20/04/2011    En intérieur  FicheMesure22985.pdf   
1512      MAUGUIO     20/04/2011    En intérieur  FicheMesure23012.pdf   
1513      BEZIERS     05/05/2011    En intérieur  FicheMesure23070.pdf   

     Conformité de la mesure  Niveau global Type d'environnement Laboratoire  
1509                     Oui           8.78    Lieu d'habitation  AEXPERTISE  
1510                     Oui           8.79    Lieu d'habitation  AEXPERTISE  
1511                     Oui           8.80    Lieu d'habitation  AEXPERTISE  
1512                     Oui           8.81    Lieu d'habitation  AEXPERTISE  
1513                     Oui           8.82    Lieu d'habitation  AEXPERTISE

In [2]:
df.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [3]:
df=df.assign(target=1)
print(df)

      Numéro de mesure  Longitude  Latitude  \
0                  175    3.91611  43.58528   
1                  180    4.04194  43.64694   
2                  543    3.03167  43.36028   
3                  545    3.03278  43.36167   
4                  850    3.56444  43.64583   
...                ...        ...       ...   
1509            160876    3.69500  43.39833   
1510            160877    3.95194  43.57361   
1511            160878    3.83972  43.60861   
1512            160879    4.00889  43.61667   
1513            160880    3.23083  43.35111   

                                       Position  Insee  \
0     03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1     04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2     03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3     03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4     03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   
...                                         ...    ...   
1509  03° 41' 42.00'' Est, 43

In [4]:
df.columns

Index(['Numéro de mesure', 'Longitude', 'Latitude', 'Position', 'Insee',
       'Adresse', 'Complément', 'Code postal', 'Commune', 'Date de mesure',
       'Mesure réalisée', 'Rapport', 'Conformité de la mesure',
       'Niveau_global', 'Type d'environnement', 'Laboratoire', 'target'],
      dtype='object')

In [5]:
def target():
    for t in range(0,len(df)):
        if (df['Niveau_global'][t]>6):
            df['target'][t] =0
            print(df['Niveau_global'][t])

In [6]:
target()

9.63
8.44
8.03
9.06
9.05
6.65
15.66
25.39
10.33
9.1
6.98
21.03
10.57
8.52
7.25
7.26
7.27
7.28
7.29
7.3
7.31
7.32
7.33
7.34
7.35
7.36
7.37
7.38
7.39
7.4
7.41
7.42
7.43
7.44
7.45
7.46
8.55
8.56
8.57
8.58
8.59
8.6
8.61
8.62
8.63
8.64
8.65
8.66
8.67
8.68
8.69
8.7
8.71
8.72
8.73
8.74
8.75
8.76
8.77
8.78
9.77
9.78
9.79
9.8
9.81
9.82
9.83
9.84
9.85
9.86
9.87
9.88
9.89
9.9
9.91
9.92
9.93
9.94
9.95
9.96
9.97
9.98
9.99
9.1
9.101
9.102
9.103
9.104
9.105
9.106
9.107000000000001
9.107999999999999
9.109
9.11
9.111
9.112
9.113
9.113999999999999
9.115
9.116
9.117
9.118
9.119
10.44
10.45
10.46
10.47
10.48
10.49
10.5
10.51
10.52
10.53
10.54
10.55
10.56
10.57
10.58
10.59
10.6
10.61
10.62
10.63
8.11
8.12
8.13
8.14
8.15
8.16
8.17
8.18
8.19
8.2
10.12
10.13
10.14
10.15
10.16
10.17
10.18
10.19
10.2
11.0
11.01
11.02
11.03
11.04
11.05
11.06
11.07
11.08
11.09
15.26
15.27
15.28
15.29
15.3
15.31
15.32
9.0
9.01
9.02
9.03
9.04
9.05
9.06
9.07
9.08
9.09
9.1
9.11
9.12
9.13
9.14
9.15
14.17
14.18
14.19
14.2
14.21
14.22
1

<ipython-input-5-0ee57b66cf66>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'][t] =0


In [7]:
pd.crosstab(df.target, "freq")

col_0   freq
target      
0        616
1        898

In [8]:
df.tail(30)

Numéro de mesure  Longitude  Latitude  \
1484            160851    3.23194  43.33611   
1485            160852    3.77889  43.43472   
1486            160853    3.68972  43.40306   
1487            160854    3.27722  43.28306   
1488            160855    3.91528  43.60417   
1489            160856    3.89361  43.60889   
1490            160857    3.87722  43.60972   
1491            160858    3.87278  43.64556   
1492            160859    3.72667  43.42917   
1493            160860    3.83556  43.63917   
1494            160861    3.90000  43.61861   
1495            160862    3.27028  43.33444   
1496            160863    3.68750  43.48778   
1497            160864    3.46667  43.31333   
1498            160865    3.84583  43.59722   
1499            160866    3.92611  43.60750   
1500            160867    3.90111  43.61861   
1501            160868    3.92694  43.58278   
1502            160869    3.89028  43.60528   
1503            160870    3.49194  43.27667   
1504            160871    3.88056  43.60139   
1505            160872    3.87972  43.60667   
1506            160873    3.85583  43.60944   
1507            160874    3.91000  43.61528   
1508            160875    3.23694  43.34556   
1509            160876    3.69500  43.39833   
1510            160877    3.95194  43.57361   
1511            160878    3.83972  43.60861   
1512            160879    4.00889  43.61667   
1513            160880    3.23083  43.35111   

                                       Position  Insee  \
1484  03° 13' 55.00'' Est, 43° 20' 10.00'' Nord  34032   
1485  03° 46' 44.00'' Est, 43° 26' 05.00'' Nord  34108   
1486  03° 41' 23.00'' Est, 43° 24' 11.00'' Nord  34301   
1487  03° 16' 38.00'' Est, 43° 16' 59.00'' Nord  34299   
1488  03° 54' 55.00'' Est, 43° 36' 15.00'' Nord  34172   
1489  03° 53' 37.00'' Est, 43° 36' 32.00'' Nord  34172   
1490  03° 52' 38.00'' Est, 43° 36' 35.00'' Nord  34172   
1491  03° 52' 22.00'' Est, 43° 38' 44.00'' Nord  34172   
1492  03° 43' 36.00'' Est, 43° 25' 45.00'' Nord  34108   
1493  03° 50' 08.00'' Est, 43° 38' 21.00'' Nord  34172   
1494  03° 53' 60.00'' Est, 43° 37' 07.00'' Nord  34172   
1495  03° 16' 13.00'' Est, 43° 20' 04.00'' Nord  34032   
1496  03° 41' 15.00'' Est, 43° 29' 16.00'' Nord  34213   
1497  03° 28' 00.00'' Est, 43° 18' 48.00'' Nord  34003   
1498  03° 50' 45.00'' Est, 43° 35' 50.00'' Nord  34172   
1499  03° 55' 34.00'' Est, 43° 36' 27.00'' Nord  34172   
1500  03° 54' 04.00'' Est, 43° 37' 07.00'' Nord  34172   
1501  03° 55' 37.00'' Est, 43° 34' 58.00'' Nord  34129   
1502  03° 53' 25.00'' Est, 43° 36' 19.00'' Nord  34172   
1503  03° 29' 31.00'' Est, 43° 16' 36.00'' Nord  34003   
1504  03° 52' 50.00'' Est, 43° 36' 05.00'' Nord  34172   
1505  03° 52' 47.00'' Est, 43° 36' 24.00'' Nord  34172   
1506  03° 51' 21.00'' Est, 43° 36' 34.00'' Nord  34172   
1507  03° 54' 36.00'' Est, 43° 36' 55.00'' Nord  34172   
1508  03° 14' 13.00'' Est, 43° 20' 44.00'' Nord  34032   
1509  03° 41' 42.00'' Est, 43° 23' 54.00'' Nord  34301   
1510  03° 57' 07.00'' Est, 43° 34' 25.00'' Nord  34198   
1511  03° 50' 23.00'' Est, 43° 36' 31.00'' Nord  34172   
1512  04° 00' 32.00'' Est, 43° 37' 00.00'' Nord  34154   
1513  03° 13' 51.00'' Est, 43° 21' 04.00'' Nord  34032   

                                        Adresse  \
1484                         28 Rue Jean Mermoz   
1485                    36 Avenue des CORMORANS   
1486                    7 Rue du Général Revest   
1487                        78 Rue Ledru Rollin   
1488                        Rue des Cauquilloux   
1489  285 Boulevard de L'aéroport International   
1490                        1 Place Jean Jaurès   
1491                       911 Avenue Agropolis   
1492                           Route de Balaruc   
1493                       245 Rue De la Galéra   
1494                       88 Rue André Malraux   
1495                          Avenue du VIGUIER   
1496                            ZI des TROUYAUX   
1497             Impasse du Command

In [9]:
X=df[['Numéro de mesure','Niveau_global']].to_numpy()
print(X)
y=df['target'].to_numpy()
print(y)

[[1.75000e+02 0.00000e+00]
 [1.80000e+02 0.00000e+00]
 [5.43000e+02 5.40000e-01]
 ...
 [1.60878e+05 8.80000e+00]
 [1.60879e+05 8.81000e+00]
 [1.60880e+05 8.82000e+00]]
[1 1 1 ... 0 0 0]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.3, random_state=0)

In [11]:
from sklearn.linear_model import LogisticRegression
#create a l.reg classifier
logreg1 = LogisticRegression()
#train the model using the training sets
logreg1.fit(X_train, y_train)
y_pred = logreg1.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[194   0]
 [261   0]]
              precision    recall  f1-score   support

           0       0.43      1.00      0.60       194
           1       0.00      0.00      0.00       261

    accuracy                           0.43       455
   macro avg       0.21      0.50      0.30       455
weighted avg       0.18      0.43      0.25       455

0.42637362637362636


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
df1=pd.read_csv('test_df1.csv',delimiter=';',encoding='latin-1')
df1.tail()

Numéro de mesure  Longitude  Latitude  \
21                22    3.83833  43.56333   
22                23    3.83083  43.58361   
23                24    3.83750  43.60556   
24                25    3.91917  43.58750   
25                26    3.92722  43.63028   

                                     Position  Insee               Adresse  \
21  03° 50' 18.00'' Est, 43° 33' 48.00'' Nord  34270     Rue Saint Exupéry   
22  03° 49' 51.00'' Est, 43° 35' 01.00'' Nord  34270   Chemin des Oliviers   
23  03° 50' 15.00'' Est, 43° 36' 20.00'' Nord  34172    Rue Viollet Le Duc   
24  03° 55' 09.00'' Est, 43° 35' 15.00'' Nord  34129  Rue du Mas de Portal   
25  03° 55' 38.00'' Est, 43° 37' 49.00'' Nord  34057    Chemin des Thermes   

                                           Complément  Code postal  \
21  Z.I. La Lauze, Unibéton, sur la passerelle de ...        34430   
22  Sur l'aire de jeux pour enfants, à côté de la ...        34430   
23    Ecole Elémentaire SPINOZA - Plateau d'évolution        34000   
24             Parking face aux maisons numéro 5 et 7        34970   
25           A l'intersection avec le chemin des Grès        34173   

                Commune Date de mesure Mesure réalisée               Rapport  \
21  SAINT-JEAN-DE-VEDAS     15/04/2010    En extérieur  FicheMesure20585.pdf   
22  SAINT-JEAN-DE-VEDAS     15/04/2010    En extérieur  FicheMesure20586.pdf   
23          MONTPELLIER     24/03/2010    En extérieur  FicheMesure20647.pdf   
24               LATTES     24/03/2010    En extérieur  FicheMesure20649.pdf   
25     CASTELNAU-LE-LEZ     11/12/2009    En extérieur  FicheMesure19212.pdf   

   Conformité de la mesure  Niveau global   Type d'environnement  \
21                     Oui           5.92                 Divers   
22                     Oui           5.93                 Divers   
23                     Oui           5.94  Rue / Route / Parking   
24                     Oui          13.56  Rue / Route / Parking   
25                     Oui           5.99  Rue / Route / Parking   

         Laboratoire  
21        AEXPERTISE  
22        AEXPERTISE  
23  EMITECH Chassieu  
24  EMITECH Chassieu  
25        AEXPERTISE

In [14]:
df1.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [15]:
df1=df1.assign(target=1)
print(df1)

    Numéro de mesure  Longitude  Latitude  \
0                  1    3.91611  43.58528   
1                  2    4.04194  43.64694   
2                  3    3.03167  43.36028   
3                  4    3.03278  43.36167   
4                  5    3.56444  43.64583   
5                  6    3.56306  43.64806   
6                  7    3.56306  43.64694   
7                  8    3.91611  43.58500   
8                  9    3.91667  43.58667   
9                 10    3.50556  43.64861   
10                11    3.50444  43.65194   
11                12    3.68444  43.40222   
12                13    3.40944  43.46028   
13                14    3.25472  43.29278   
14                15    3.20556  43.32667   
15                16    3.83833  43.56333   
16                17    3.83083  43.58361   
17                18    3.83750  43.60556   
18                19    3.91917  43.58750   
19                20    3.92722  43.63028   
20                21    3.20556  43.32667   
21        

In [16]:
def target1():
    for t in range(0,len(df1)):
        if (df1['Niveau_global'][t]>6):
            df1['target'][t] =0
            print(df1['Niveau_global'][t])

In [17]:
target1()

7.41
6.42
6.43
6.5
6.42
6.43
6.5
6.42
6.43
13.56
14.57
13.56


<ipython-input-16-eec2a1304826>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['target'][t] =0


In [18]:
Z=df1[['Numéro de mesure','Niveau_global']].to_numpy()
print(Z)
z=df1['target'].to_numpy()
print(z)

[[ 1.    0.  ]
 [ 2.    0.  ]
 [ 3.    0.54]
 [ 4.    0.2 ]
 [ 5.    0.53]
 [ 6.    0.78]
 [ 7.    0.53]
 [ 8.    0.  ]
 [ 9.    0.54]
 [10.    7.41]
 [11.    6.42]
 [12.    6.43]
 [13.    6.5 ]
 [14.    6.42]
 [15.    6.43]
 [16.    6.5 ]
 [17.    6.42]
 [18.    6.43]
 [19.   13.56]
 [20.   14.57]
 [21.    5.91]
 [22.    5.92]
 [23.    5.93]
 [24.    5.94]
 [25.   13.56]
 [26.    5.99]]
[1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1]


In [19]:
y1_pred=logreg1.predict(Z)
print(y1_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(z,y1_pred))
print(classification_report(z, y1_pred))
print(accuracy_score(z, y1_pred))

[[12  0]
 [14  0]]
              precision    recall  f1-score   support

           0       0.46      1.00      0.63        12
           1       0.00      0.00      0.00        14

    accuracy                           0.46        26
   macro avg       0.23      0.50      0.32        26
weighted avg       0.21      0.46      0.29        26

0.46153846153846156


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
